2024-12-15 23:21:06,748 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Обучение\python\ДЗ\module_12\tests_12_4.py", line 26, in test_run
    self.runner_2 = Runner(2)
                    ^^^^^^^^^
  File "C:\Обучение\python\ДЗ\module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-15 23:21:06,751 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Обучение\python\ДЗ\module_12\tests_12_4.py", line 15, in test_walk
    self.runner_1 = Runner('1', -3)
                    ^^^^^^^^^^^^^^^
  File "C:\Обучение\python\ДЗ\module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -3
